################################################################################
# These macros are used by makefiles and argument files.
# When a space is included in the path and quotes (") cannot be used,
# a _ESCAPE version of the macro is added that escapes the space with backslash (\).
################################################################################

export SNMP=C:/Freescale/Freescale_MQX_4_0/rtcs/examples/snmp
export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export ProjDirPath=C:/Freescale/Freescale_MQX_4_0/rtcs/examples/snmp/cw10/snmp_twrk60d100m
export EXAMPLES=C:/Freescale/Freescale_MQX_4_0/rtcs/examples
export CWInstallLocationEnv=C:/Freescale/CW MCU v10.4
export MCUToolsBaseDirEnv=$(CWInstallLocationEnv)/MCU
export BSP=C:/Freescale/Freescale_MQX_4_0/lib/twrk60d100m.cw10/debug/bsp
export TWRK60D100M_CW10=C:/Freescale/Freescale_MQX_4_0/lib/twrk60d100m.cw10
export ARM_ToolsDirEnv=$(CWInstallLocationEnv)/MCU/ARM_Tools/Command_Line_Tools
export DEBUG=C:/Freescale/Freescale_MQX_4_0/lib/twrk60d100m.cw10/debug
