################################################################################
# These macros are used by makefiles and argument files.
# When a space is included in the path and quotes (") cannot be used,
# a _ESCAPE version of the macro is added that escapes the space with backslash (\).
################################################################################

export ProjDirPath=D:/projects/Freescale/Freescale_MQX_4_0/rtcs/examples/snmp_brad/cw10/SymcomDemo
export ARM_ToolsDirEnv=$(CWInstallLocationEnv)/MCU/ARM_Tools/Command_Line_Tools
export DEBUG=D:/projects/Freescale/Freescale_MQX_4_0/lib/twrk60n512.cw10/debug
export BSP=D:/projects/Freescale/Freescale_MQX_4_0/lib/twrk60n512.cw10/debug/bsp
export SNMP=D:/projects/Freescale/Freescale_MQX_4_0/rtcs/examples/snmp
export GNU_Make_Install_DirEnv=$(CWInstallLocationEnv)/gnu/bin
export CWInstallLocationEnv=D:/Freescale/CW MCU v10.4
export TWRK60N512_CW10=D:/projects/Freescale/Freescale_MQX_4_0/lib/twrk60n512.cw10
export EXAMPLES=D:/projects/Freescale/Freescale_MQX_4_0/rtcs/examples
export MCUToolsBaseDirEnv=$(CWInstallLocationEnv)/MCU
export SNMP_BRAD=D:/projects/Freescale/Freescale_MQX_4_0/rtcs/examples/snmp_brad
